"use client";
/* eslint-disable react-hooks/set-state-in-effect, react/no-unescaped-entities, react-hooks/purity */

import { useEffect, useMemo, useState } from "react";
import { compareSessions, recommendDifficulty, type Performance } from "@/lib/adaptive";
import { games, type GameDefinition, type GameId } from "@/lib/game-catalog";
import { localeNames, messages, type Locale } from "@/lib/i18n";
import styles from "./mindmitra-app.module.css";

type Role = "landing" | "elder" | "caregiver";
type View = "day" | "games" | "memories" | "assistant" | "reports" | "reminders" | "safety";
type Reminder = { id: string; title: string; time: string; type: string; done: boolean; snoozed?: boolean };
type StoredResult = Performance & { gameId: GameId; game: string; at: string };

const starterReminders: Reminder[] = [
  { id: "medicine", title: "Morning medicine", time: "09:00", type: "Medicine", done: false },
  { id: "water", title: "Drink a glass of water", time: "10:30", type: "Hydration", done: false },
  { id: "call", title: "Family call with Maya", time: "16:00", type: "Connection", done: false },
];
const starterResults: StoredResult[] = [
  { gameId: "tile-memory", game: "Tile Memory Matcher", accuracy: 62, completionTimeMs: 94000, mistakes: 5, hintsUsed: 3, attempts: 1, difficulty: 1, at: "Previous week" },
  { gameId: "tile-memory", game: "Tile Memory Matcher", accuracy: 84, completionTimeMs: 67000, mistakes: 2, hintsUsed: 1, attempts: 1, difficulty: 2, at: "Yesterday" },
];

export default function MindMitraApp() {
  const [role, setRole] = useState<Role>("landing"), [view, setView] = useState<View>("day"), [locale, setLocale] = useState<Locale>("en");
  const [dark, setDark] = useState(false), [large, setLarge] = useState(1), [contrast, setContrast] = useState(false), [offline, setOffline] = useState(false);
  const [reminders, setReminders] = useState<Reminder[]>(starterReminders), [results, setResults] = useState<StoredResult[]>(starterResults), [game, setGame] = useState<GameDefinition | null>(null), [notice, setNotice] = useState("");
  const text = messages[locale];
  useEffect(() => { const saved = localStorage.getItem("mindmitra-demo"); if (saved) { const data = JSON.parse(saved); setReminders(data.reminders || starterReminders); setResults(data.results || starterResults); setLocale(data.locale || "en"); setDark(!!data.dark); setLarge(data.large || 1); setContrast(!!data.contrast); } const network = () => setOffline(!navigator.onLine); network(); addEventListener("online", network); addEventListener("offline", network); return () => { removeEventListener("online", network); removeEventListener("offline", network); }; }, []);
  useEffect(() => localStorage.setItem("mindmitra-demo", JSON.stringify({ reminders, results, locale, dark, large, contrast })), [reminders, results, locale, dark, large, contrast]);
  useEffect(() => { if (!notice) return; const timer = setTimeout(() => setNotice(""), 3500); return () => clearTimeout(timer); }, [notice]);
  const next = reminders.find((item) => !item.done && !item.snoozed);
  const difficulty = useMemo(() => results.filter((item) => item.gameId === "tile-memory").at(-1)?.difficulty || 1, [results]);
  const finish = (definition: GameDefinition, result: Performance) => { setResults((all) => [...all, { ...result, gameId: definition.id, game: definition.title, at: "Just now" }]); setGame(null); setView("reports"); setNotice("Result saved locally. Your before-and-after activity insight is now open."); };
  const reminderAction = (id: string, action: "done" | "snooze" | "help") => { if (action === "help") { setNotice("Help request recorded locally. A configured provider is required to deliver an alert."); return; } setReminders((all) => all.map((item) => item.id === id ? { ...item, done: action === "done", snoozed: action === "snooze" } : item)); setNotice(action === "done" ? "Reminder completed." : "Reminder moved forward by 15 minutes."); };
  if (role === "landing") return <Landing enter={(selected) => { setRole(selected); setView(selected === "elder" ? "day" : "reports"); }} />;
  if (game) return <GamePlayer definition={game} difficulty={difficulty} exit={() => setGame(null)} complete={finish} />;
  const nav: [View, string, string][] = role === "elder" ? [["day", text.myDay, "☀"], ["games", text.games, "◇"], ["memories", text.memories, "▣"], ["assistant", text.assistant, "◌"]] : [["reports", "Reports", "↗"], ["reminders", "Reminders", "◷"], ["memories", "Memories", "▣"], ["safety", "Safety", "⌖"]];
  return <div className={styles.app + (dark ? " " + styles.dark : "") + (contrast ? " " + styles.contrast : "")} style={{ fontSize: (16 + large * 2) + "px" }}>
    <a className={styles.skip} href="#main">Skip to content</a><header className={styles.topbar}><button className={styles.brand} onClick={() => setView(role === "elder" ? "day" : "reports")}><b>M</b><span>MindMitra<small>Together, every day</small></span></button><div className={styles.controls}><select aria-label="Language" value={locale} onChange={(event) => setLocale(event.target.value as Locale)}>{Object.entries(localeNames).map(([id, label]) => <option key={id} value={id}>{label}</option>)}</select><button onClick={() => setDark(!dark)} aria-label="Toggle theme">{dark ? "☼" : "◐"}</button><button onClick={() => setLarge((value) => (value + 1) % 4)} aria-label="Change text size">Aᴀ</button></div></header>
    {offline && <div className={styles.offline}>Offline · reminders and games stay available. New results are stored locally until you reconnect.</div>}
    <div className={styles.shell}><aside className={styles.sidebar}><div className={styles.person}><b>{role === "elder" ? "A" : "M"}</b><span><strong>{role === "elder" ? "Asha Devi" : "Maya Devi"}</strong><small>{role === "elder" ? "Your day, at your pace" : "Caregiver · Asha's circle"}</small></span></div><nav>{nav.map(([id, label, icon]) => <button key={id} className={view === id ? styles.active : ""} onClick={() => setView(id)}><i>{icon}</i><span>{label}</span></button>)}</nav><div className={styles.sidebarBottom}><button onClick={() => setContrast(!contrast)}>◉ High contrast</button><button onClick={() => setRole("landing")}>↩ Exit demo</button></div></aside>
      <main id="main" className={styles.main}>{role === "elder" && view === "day" && <Day text={text} next={next} reminders={reminders} action={reminderAction} go={setView} />}{role === "elder" && view === "games" && <Games difficulty={difficulty} results={results} open={setGame} />}{role === "elder" && view === "memories" && <Memories />}{role === "elder" && view === "assistant" && <Assistant reminders={reminders} go={setView} />}{role === "caregiver" && view === "reports" && <Reports results={results} reminders={reminders} open={() => { setRole("elder"); setView("games"); }} />}{role === "caregiver" && view === "reminders" && <ReminderManager reminders={reminders} setReminders={setReminders} />}{role === "caregiver" && view === "memories" && <Memories caregiver />}{role === "caregiver" && view === "safety" && <Safety />}</main>
    </div>{notice && <div className={styles.toast} role="status">{notice}</div>}
  </div>;
}

function Landing({ enter }: { enter: (role: "elder" | "caregiver") => void }) { return <main className={styles.landing}><div className={styles.landscape}><i /><b /><em /></div><header><div className={styles.brand}><b>M</b>MindMitra</div><span>Designed for familiar moments</span></header><section><p>SIH26003 · NORTH EAST INDIA</p><h1>Remember More.<br />Live Independently.<br /><em>Stay Connected.</em></h1><div className={styles.landingCopy}>A gentle companion for daily assistance, cognitive engagement, familiar memories, and connected caregiving. It supports participation and does not diagnose or treat medical conditions.</div><div className={styles.entryCards}><button onClick={() => enter("elder")}><i>☀</i><strong>Enter Asha&apos;s day</strong><small>Large, calm daily support</small><b>Start demo →</b></button><button onClick={() => enter("caregiver")}><i>◫</i><strong>Caregiver portal</strong><small>Trends, reminders & memories</small><b>View dashboard →</b></button></div><div className={styles.featureStrip}><span>6 languages</span><span>Voice-friendly</span><span>Low-connectivity ready</span><span>Northeast moments</span></div></section></main>; }
function Header({ eyebrow, title, text, action }: { eyebrow: string; title: string; text: string; action?: React.ReactNode }) { return <div className={styles.heading}><div><p>{eyebrow}</p><h1>{title}</h1><span>{text}</span></div>{action}</div>; }
function Day({ text, next, reminders, action, go }: { text: Record<string, string>; next?: Reminder; reminders: Reminder[]; action: (id: string, action: "done" | "snooze" | "help") => void; go: (view: View) => void }) { return <><Header eyebrow="TUESDAY · 15 SEPTEMBER" title={text.greeting} text="It is a beautiful day. Let us take it one gentle step at a time." action={<div className={styles.clock}><b>09:18</b><small>Tuesday morning</small></div>} /><div className={styles.twoCol}><section className={styles.card + " " + styles.nextCard}><p>UP NEXT</p><h2>{next?.title || "You are all caught up"}</h2><span>{next?.time} · A small, important step for your day.</span>{next && <div className={styles.actions}><button className={styles.primary} onClick={() => action(next.id, "done")}>{text.done}</button><button onClick={() => action(next.id, "snooze")}>{text.later}</button><button className={styles.danger} onClick={() => action(next.id, "help")}>{text.help}</button></div>}</section><section className={styles.card}><p>TODAY&apos;S GENTLE PLAN</p>{reminders.map((item) => <div className={styles.timeline} key={item.id}><i className={item.done ? styles.done : ""}>{item.done ? "✓" : "○"}</i><div><b>{item.title}</b><small>{item.time} · {item.done ? "Completed" : item.snoozed ? "Snoozed" : "Coming up"}</small></div></div>)}</section></div><div className={styles.sectionTitle}><div><p>A LITTLE FOR YOU</p><h2>Choose what feels good today</h2></div><button onClick={() => go("games")}>All activities →</button></div><div className={styles.choiceGrid}><Choice icon="◇" title="Play a gentle game" text="Memory, attention & recall" click={() => go("games")} /><Choice icon="▣" title="Look at memories" text="Family, places & stories" click={() => go("memories")} /><Choice icon="◌" title="Ask MindMitra" text="What is next?" click={() => go("assistant")} /></div></>; }
function Choice({ icon, title, text, click }: { icon: string; title: string; text: string; click: () => void }) { return <button className={styles.choice} onClick={click}><i>{icon}</i><strong>{title}</strong><small>{text}</small></button>; }
function Games({ difficulty, results, open }: { difficulty: number; results: StoredResult[]; open: (game: GameDefinition) => void }) { const latest = results.filter((item) => item.gameId === "tile-memory").at(-1); return <><Header eyebrow="COGNITIVE ENGAGEMENT" title="Activities at your pace" text="Ten playable activities with start, result, restart, exit, and accessible controls." action={<button className={styles.outline} onClick={() => speechSynthesis.speak(new SpeechSynthesisUtterance("Take your time. You are doing very well."))}>◌ Listen</button>} /><section className={styles.card + " " + styles.recommend}><b>✦</b><div><strong>Today&apos;s adaptive suggestion</strong><p>{latest ? "Tile Memory Matcher is suggested at level " + difficulty + ". " + recommendDifficulty(latest).message : "Start with a gentle level. MindMitra will make the next suggestion from activity results."}</p></div></section><div className={styles.gameGrid}>{games.map((item) => <button key={item.id} className={styles.gameCard} onClick={() => open(item)}><i>{item.icon}</i><span>{item.category}</span><strong>{item.title}</strong><small>{item.description}</small><b>Play →</b></button>)}</div></>; }
function GamePlayer({ definition, difficulty, exit, complete }: { definition: GameDefinition; difficulty: number; exit: () => void; complete: (game: GameDefinition, result: Performance) => void }) { const [phase, setPhase] = useState<"start" | "play" | "result">("start"), [mistakes, setMistakes] = useState(0), [hints, setHints] = useState(0), [started, setStarted] = useState(0); const performance = { accuracy: Math.max(40, 100 - mistakes * 12 - hints * 5), completionTimeMs: Math.max(1000, Date.now() - started), mistakes, hintsUsed: hints, difficulty, attempts: 1 }; return <main className={styles.gameShell}><button className={styles.back} onClick={exit}>← Exit activity</button><section className={styles.gamePanel}><p>GENTLE ACTIVITY · {definition.category.toUpperCase()}</p><h1>{definition.title}</h1><span>{definition.instructions}</span>{phase === "start" && <div className={styles.start}><p>Difficulty: <b>{["Easy", "Comfortable", "More challenge"][difficulty - 1]}</b></p><button className={styles.primary} onClick={() => { setStarted(Date.now()); setPhase("play"); }}>Start activity</button></div>}{phase === "play" && <Activity id={definition.id} difficulty={difficulty} hint={() => setHints((value) => value + 1)} mistake={() => setMistakes((value) => value + 1)} finish={() => setPhase("result")} />}{phase === "result" && <div className={styles.result}><b>Activity complete</b><h2>{performance.accuracy}% participation score</h2><div><span>Accuracy <strong>{performance.accuracy}%</strong></span><span>Mistakes <strong>{mistakes}</strong></span><span>Hints <strong>{hints}</strong></span></div><p>{recommendDifficulty(performance).message}</p><button className={styles.primary} onClick={() => complete(definition, performance)}>View my activity insight</button><button onClick={() => { setPhase("start"); setMistakes(0); setHints(0); }}>Restart</button></div>}</section></main>; }
function Activity({ id, difficulty, hint, mistake, finish }: { id: GameId; difficulty: number; hint: () => void; mistake: () => void; finish: () => void }) { if (id === "tile-memory" || id === "picture-pairs") return <MemoryGame symbols={id === "tile-memory" ? ["◆", "●", "▲", "■", "☀", "☾"] : ["☕", "⌂", "✿", "♬", "☘", "⌁"]} pairs={difficulty === 1 ? 3 : difficulty === 2 ? 4 : 6} mistake={mistake} finish={finish} />; if (id === "arrows") return <ArrowGame mistake={mistake} finish={finish} />; if (id === "number-grid") return <NumberGame max={difficulty === 1 ? 5 : difficulty === 2 ? 8 : 12} mistake={mistake} finish={finish} />; if (id === "routine") return <SequenceGame mistake={mistake} finish={finish} />; if (id === "tambola") return <Tambola difficulty={difficulty} hint={hint} mistake={mistake} finish={finish} />; const data: Record<string, [string, string[], string, boolean]> = { missing: ["The tea cup was removed. Which object is missing?", ["Tea cup", "Bamboo basket", "Book"], "Tea cup", false], story: ["Maya brought Asha a warm shawl before the evening rain. What did Maya bring?", ["A warm shawl", "A bicycle", "A mango tree"], "A warm shawl", false], categories: ["Where does a banana belong?", ["Food", "Clothing", "Household"], "Food", false], instrument: ["Listen to an original gentle tone, then choose the instrument-inspired sound.", ["Bamboo flute", "Car horn", "Telephone"], "Bamboo flute", true] }; const item = data[id]; return <ChoiceGame prompt={item[0]} choices={item[1]} answer={item[2]} audio={item[3]} mistake={mistake} finish={finish} />; }
function ChoiceGame({ prompt, choices, answer, audio, mistake, finish }: { prompt: string; choices: string[]; answer: string; audio: boolean; mistake: () => void; finish: () => void }) { return <div className={styles.round}>{audio && <button className={styles.listen} onClick={() => { const context = new AudioContext(); const oscillator = context.createOscillator(); oscillator.frequency.value = 540; oscillator.connect(context.destination); oscillator.start(); setTimeout(() => { oscillator.stop(); context.close(); }, 600); }}>▷ Play safe tone</button>}<h2>{prompt}</h2><div className={styles.answers}>{choices.map((choice) => <button key={choice} onClick={() => choice === answer ? finish() : mistake()}>{choice}</button>)}</div></div>; }
function ArrowGame({ mistake, finish }: { mistake: () => void; finish: () => void }) { const [step, setStep] = useState(0); const sequence = ["→", "↑", "←"]; const target = sequence[step]; return <div className={styles.round}><div className={styles.arrow}>{target}</div><h2>Select this arrow · step {step + 1} of 3</h2><div className={styles.arrowButtons}>{["↑", "→", "↓", "←"].map((arrow) => <button key={arrow} onClick={() => arrow === target ? step === 2 ? finish() : setStep(step + 1) : mistake()}>{arrow}</button>)}</div></div>; }
function NumberGame({ max, mistake, finish }: { max: number; mistake: () => void; finish: () => void }) { const [next, setNext] = useState(1); const list = Array.from({ length: max }, (_, index) => index + 1).sort((a, b) => (a * 13) % 7 - (b * 13) % 7); return <div className={styles.round}><h2>Find {next}</h2><div className={styles.numberGrid}>{list.map((number) => <button key={number} onClick={() => number === next ? next === max ? finish() : setNext(next + 1) : mistake()}>{number}</button>)}</div></div>; }
function SequenceGame({ mistake, finish }: { mistake: () => void; finish: () => void }) { const values = ["Wake up", "Brush teeth", "Breakfast", "Medicine", "Activity"]; const [next, setNext] = useState(0); const choices = [values[2], values[0], values[4], values[1], values[3]]; return <div className={styles.round}><h2>Tap the next part of a familiar morning routine</h2><div className={styles.answers}>{choices.map((value) => <button key={value} disabled={next > values.indexOf(value)} onClick={() => value === values[next] ? next === values.length - 1 ? finish() : setNext(next + 1) : mistake()}>{value}</button>)}</div></div>; }
function MemoryGame({ symbols, pairs, mistake, finish }: { symbols: string[]; pairs: number; mistake: () => void; finish: () => void }) { const cards = symbols.slice(0, pairs).flatMap((symbol) => [symbol, symbol]); const order = cards.map((_, index) => (index * 5 + 3) % cards.length); const [open, setOpen] = useState<number[]>([]), [matched, setMatched] = useState<number[]>([]); const hit = (index: number) => { if (open.includes(index) || matched.includes(index) || open.length === 2) return; const chosen = [...open, index]; setOpen(chosen); if (chosen.length === 2) { if (cards[order[chosen[0]]] === cards[order[chosen[1]]]) { const all = [...matched, ...chosen]; setMatched(all); setOpen([]); if (all.length === cards.length) finish(); } else { mistake(); setTimeout(() => setOpen([]), 550); } } }; return <div className={styles.memoryCards}>{cards.map((_, index) => <button className={open.includes(index) || matched.includes(index) ? styles.flipped : ""} key={index} onClick={() => hit(index)}>{open.includes(index) || matched.includes(index) ? cards[order[index]] : "?"}</button>)}</div>; }
function Tambola({ difficulty, hint, mistake, finish }: { difficulty: number; hint: () => void; mistake: () => void; finish: () => void }) { const calls = difficulty === 1 ? [4, 9, 15] : [4, 9, 15, 18]; const [index, setIndex] = useState(0); const board = [2, 4, 6, 9, 12, 15, 18, 22, 25]; return <div className={styles.round}><h2>Find number {calls[index]}</h2><button className={styles.outline} onClick={hint}>Show a hint</button><div className={styles.numberGrid}>{board.map((number) => <button key={number} onClick={() => number === calls[index] ? index === calls.length - 1 ? finish() : setIndex(index + 1) : mistake()}>{number}</button>)}</div></div>; }
function Memories({ caregiver = false }: { caregiver?: boolean }) { const cards = [["⌂", "My Family", "Maya, Rohan & family"], ["⌁", "My Village", "Jorhat, Assam"], ["✿", "Festivals", "Bihu memories"], ["◒", "My Northeast", "Landmarks, food & sounds"]]; return <><Header eyebrow="FAMILIAR STORIES" title={caregiver ? "Asha's memories" : "Your memories"} text={caregiver ? "Only approved caregivers can add or view these personal items." : "People and places close to your heart."} action={caregiver ? <button className={styles.primary}>+ Add a memory</button> : undefined} /><div className={styles.memoryGrid}>{cards.map(([icon, title, caption]) => <article className={styles.memory} key={title}><i>{icon}</i><strong>{title}</strong><small>{caption}</small><button>Open collection →</button></article>)}</div><section className={styles.card + " " + styles.comfort}><i>♫</i><div><strong>Comfort sounds</strong><p>Original bamboo-flute-inspired tones, river ambience and birds. No copyrighted recordings are used.</p></div><button className={styles.outline}>▷ Play river ambience</button></section></>; }
function Assistant({ reminders, go }: { reminders: Reminder[]; go: (view: View) => void }) { const [question, setQuestion] = useState(""), [answer, setAnswer] = useState("Hello Asha. I can help with your day, reminders, games, and memories."); const submit = () => { const q = question.toLowerCase(), next = reminders.find((item) => !item.done); const value = q.includes("next") || q.includes("today") ? next ? "Your next reminder is " + next.title + " at " + next.time + "." : "You have completed everything planned for today." : q.includes("game") ? "You can choose from ten memory, attention, recall, sequencing, recognition, and Northeast activities." : q.includes("memory") ? "I can open your memories now." : "I can help with your day, your next reminder, games, or memories."; setAnswer(value); speechSynthesis.speak(new SpeechSynthesisUtterance(value)); if (q.includes("memory")) go("memories"); setQuestion(""); }; return <><Header eyebrow="YOUR GENTLE HELPER" title="Ask MindMitra" text="Core requests work locally when an AI provider is unavailable." /><section className={styles.card + " " + styles.assistant}><i>◌</i><p>{answer}</p><form onSubmit={(event) => { event.preventDefault(); submit(); }}><input value={question} onChange={(event) => setQuestion(event.target.value)} placeholder="What do I have today?" /><button className={styles.primary}>Ask</button></form><div><button onClick={() => setQuestion("What is my next reminder?")}>What is next?</button><button onClick={() => setQuestion("What games can I play?")}>What games can I play?</button><button onClick={() => setQuestion("Show my memories")}>Show my memories</button></div></section></>; }
function Reports({ results, reminders, open }: { results: StoredResult[]; reminders: Reminder[]; open: () => void }) { const tile = results.filter((item) => item.gameId === "tile-memory"), before = tile[0], after = tile.at(-1); const average = Math.round(results.reduce((sum, item) => sum + item.accuracy, 0) / results.length); return <><Header eyebrow="ASHA'S CARE CIRCLE" title="Activity overview" text="Participation trends support caring conversations; they are not medical assessments." action={<button className={styles.primary} onClick={open}>Open Asha's games</button>} /><div className={styles.metrics}><Metric value={String(results.length)} label="Activities saved" note="On this demo device" /><Metric value={average + "%"} label="Typical accuracy" note="Activity performance only" /><Metric value={reminders.filter((item) => item.done).length + "/" + reminders.length} label="Reminders completed" note="Today" /><Metric value="Safe" label="Safety status" note="Demo zone active" /></div><div className={styles.twoCol}><section className={styles.card}><p>FLAGSHIP ACTIVITY</p><h2>Tile Memory Matcher · Before & After</h2><div className={styles.compare}><div><span>Previous</span><b>{before?.accuracy || 0}%</b><small>{Math.round((before?.completionTimeMs || 0) / 1000)} sec · {before?.hintsUsed || 0} hints</small></div><div><span>Current</span><b>{after?.accuracy || 0}%</b><small>{Math.round((after?.completionTimeMs || 0) / 1000)} sec · {after?.hintsUsed || 0} hints</small></div></div><p className={styles.insight}>{compareSessions(before, after || before)}</p></section><section className={styles.card}><p>RECENT ACTIVITY</p><h2>Participation pattern</h2><div className={styles.bars}>{results.slice(-7).map((item, index) => <div key={index}><i style={{ height: item.accuracy + "%" }} /><small>{item.at === "Just now" ? "Now" : item.at.slice(0, 3)}</small></div>)}</div><p className={styles.insight}>Results shown here come from actual completed demo activities on this device.</p></section></div><GameWiseReports results={results} /></>; }
function GameWiseReports({ results }: { results: StoredResult[] }) { const grouped = results.reduce((all, item) => { (all[item.gameId] ||= []).push(item); return all; }, {} as Partial<Record<GameId, StoredResult[]>>); return <section className={styles.gameReports}><div><p>CARETAKER VIEW</p><h2>Game-wise activity details</h2><span>Use these observed participation patterns to guide comfort and encouragement. They are not a medical assessment.</span></div>{Object.entries(grouped).map(([gameId, sessions]) => { const list = sessions!; const latest = list.at(-1)!; const average = Math.round(list.reduce((sum, item) => sum + item.accuracy, 0) / list.length); const averageHints = (list.reduce((sum, item) => sum + item.hintsUsed, 0) / list.length).toFixed(1); const guidance = latest.accuracy >= 80 && latest.hintsUsed <= 1 ? "Comfortable participation; offer a similar or gently more challenging activity." : latest.accuracy < 65 || latest.hintsUsed >= 3 ? "Consider simpler settings, fewer items, and audio or visual guidance next time." : "Steady participation; maintain the current level and observe comfort."; return <article className={styles.gameReport} key={gameId}><header><strong>{latest.game}</strong><span>{list.length} session{list.length === 1 ? "" : "s"}</span></header><div><b>{average}%<small>average accuracy</small></b><b>{Math.round(latest.completionTimeMs / 1000)}s<small>latest time</small></b><b>{latest.mistakes}<small>latest mistakes</small></b><b>{averageHints}<small>average hints</small></b><b>Level {latest.difficulty}<small>latest difficulty</small></b></div><p>{guidance}</p></article>; })}</section>; }
function Metric({ value, label, note }: { value: string; label: string; note: string }) { return <section className={styles.card + " " + styles.metric}><b>{value}</b><strong>{label}</strong><small>{note}</small></section>; }
function ReminderManager({ reminders, setReminders }: { reminders: Reminder[]; setReminders: React.Dispatch<React.SetStateAction<Reminder[]>> }) { const [title, setTitle] = useState(""), [time, setTime] = useState("12:00"); const add = (event: React.FormEvent) => { event.preventDefault(); if (!title.trim()) return; setReminders((items) => [...items, { id: crypto.randomUUID(), title: title.trim(), time, type: "Important task", done: false }]); setTitle(""); }; return <><Header eyebrow="DAILY ASSISTANCE" title="Reminder management" text="Demo reminders persist on this device. Signed-in accounts use the protected reminder API." /><section className={styles.card}><form className={styles.addReminder} onSubmit={add}><input required value={title} onChange={(event) => setTitle(event.target.value)} placeholder="Reminder title" /><input type="time" value={time} onChange={(event) => setTime(event.target.value)} /><button className={styles.primary}>Add reminder</button></form>{reminders.map((item) => <div className={styles.reminderRow} key={item.id}><div><b>{item.title}</b><small>{item.type} · {item.time}</small></div><span className={styles.badge}>{item.done ? "Done" : item.snoozed ? "Snoozed" : "Scheduled"}</span></div>)}</section><section className={styles.card + " " + styles.escalation}><i>◷</i><div><strong>Escalation is configurable</strong><p>Medicine reminders may repeat locally, then notify a caregiver through a configured provider. MindMitra does not claim to send SMS or alerts unless one is connected.</p></div></section></>; }
function Safety() { const [enabled, setEnabled] = useState(false); return <><Header eyebrow="OPTIONAL · CONSENT-BASED" title="Safety zone" text="Location sharing is off by default and can be disabled at any time." action={<button className={enabled ? styles.primary : styles.outline} onClick={() => setEnabled(!enabled)}>{enabled ? "Tracking enabled" : "Enable demo tracking"}</button>} /><section className={styles.card + " " + styles.safety}><div className={styles.map}><span>Home</span><i>⌖</i><small>Demo map · Jorhat, Assam</small></div><div><span className={styles.good}>● {enabled ? "Within safe zone" : "Tracking is off"}</span><h2>Home area · 300 m radius</h2><p>This demo does not access a device location. Production location events require consent and caregiver authorization.</p><button className={styles.outline}>Manage emergency contacts</button></div></section></>; }
